### ISSUE TITLE
solis_modbus.write_holding_register fails to update the discharge current

### ISSUE THREAD

**Issue by ctepelea** [Pho3niX90/solis_modbus#132]
I am getting this error when doing the service call to solis_modbus.solis_write_holding_register. What could be the issue?

action: solis_modbus.solis_write_holding_register
metadata: {}
data:
  address: 43142
  value: >-
    {{ max(min(-(states("sensor.pm_net_power") | float /50 -
    states("number.solis_s6_solis_time_charging_discharge_current")|float) |
    round(1),100),4) * 10}}

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/b5eab5d8-ef5b-45f6-8163-65f6b7499e48" />

Logger: homeassistant.components.automation.energy_solis_discharge_current_tracks_net_consumption
Source: helpers/script.py:526
integration: Automation (documentation, issues)
First occurred: 21:11:20 (294 occurrences)
Last logged: 22:51:20

Energy: Battery Discharge - Tracks Net Consumption: Error executing script. Unexpected error for call_service at pos 2: 'NodeDictClass' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 762, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2844, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solis_modbus/__init__.py", line 29, in service_write_holding_register
    host = entry.data.get("host")
           ^^^^^^^^^^
AttributeError: 'NodeDictClass' object has no attribute 'data'

**Comment by 0rangutan** [comment]
Are you on the latest Solis firmware (6 rather than 3 charging slots)?

**Comment by Pho3niX90** [comment]
This should resolve that https://github.com/Pho3niX90/solis_modbus/releases/tag/2.1.1

**Comment by ctepelea** [comment]
Hello and thanks for the quick turnaround. However now the integration does not load at all, see below.

Logger: homeassistant.setup
Source: setup.py:409
First occurred: 10:26:50 (1 occurrences)
Last logged: 10:26:50

Just for reference if it makes a difference, I am using a Solis S5-EH1P6K-L-DC inverter with an S2 datalogger.

Error during setup of component solis_modbus: async_setup() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 409, in _async_setup_component
    task = component.async_setup(hass, processed_config)
TypeError: async_setup() takes 1 positional argument but 2 were given

<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/55e6fc09-e478-4139-8ee8-37bfdbc29e7f" />

**Comment by Pho3niX90** [comment]
I have released a fix for this as well now, an oversight from my part:
https://github.com/Pho3niX90/solis_modbus/releases/tag/2.1.2

**Comment by ctepelea** [comment]
Thanks. That's really great speed. Unfortunately I still can't make it work.

Executed: 16 February 2025 at 16:54:50
Error: 'str' object has no attribute 'write_holding_register'
Result:
params:
  domain: solis_modbus
  service: solis_write_holding_register
  service_data:
    address: 43141
    value: 30
  target: {}
running_script: false

<img width="1461" alt="Image" src="https://github.com/user-attachments/assets/aac73804-1ebf-4a23-9cdc-f0f7c3bc6173" />

Logger: homeassistant.components.automation.energy_solis_charge_tracks_ac_total_output
Source: helpers/script.py:526
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 13:17:30 (1315 occurrences)
Last logged: 16:56:30

Energy: Solar Charge - Track AC Total Output: Error executing script. Unexpected error for call_service at pos 2: 'str' object has no attribute 'write_holding_register'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 762, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2844, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solis_modbus/__init__.py", line 36, in service_write_holding_register
    hass.create_task(controller.write_holding_register(address, value))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write_holding_register'

**Comment by Pho3niX90** [comment]
@ctepelea can you use it from the developer view? I believe it's `script.solis_write_holding_register`

**Comment by ctepelea** [comment]
<img width="836" alt="Image" src="https://github.com/user-attachments/assets/876ab617-2046-41c5-84b1-7a067de8429e" />

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 19:17:57 (6 occurrences)
Last logged: 19:21:07

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'str' object has no attribute 'write_holding_register'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 762, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2844, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solis_modbus/__init__.py", line 36, in service_write_holding_register
    hass.create_task(controller.write_holding_register(address, value))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write_holding_register'

**Comment by Pho3niX90** [comment]
I am investigating this, I believe this became an issue when I tried to better the multiple inverter support. 

In the meantime, it might be easier to set the actual `number.solis_inverter_time_charging_charge_current` for this example.

**Comment by ctepelea** [comment]
Before I upgraded to 2.0, setting the number.solis_inverter_time_charging_charge_current was resulting in the inverters charge/discharge current being affecter in 8 out of 10 calls. And I was happy, it took maybe 10 seconds or so but it was working. After upgrading to the 2.0 version, setting the current via the input entity takes a very long time and 9 out of 10 the integration re-reads the currently set value in solis_s6_solis_time_charging_charge_current back to the number.solis_inverter_time_charging_charge_current before the newly set value is written to the inverter. So this is not working.

The workaround I thought about was to go back to the fbondy/modbus implementation and then it works very fast because I limited the number of registers being read/written. I cannot have also your integration and the modbus native HA working at the same time as you cannot have two connection simultaneously.

This is when I decided to try to write directly via solis_modbus.service_write_holding_register the charge current/discharge current register.

I hope this makes sense to you. If you want to try something is to prioritise writing the charge/discharge current registers when the respective input_number changes.

**Comment by Pho3niX90** [comment]
Which inverter are you currently using?

Could you provide me in txt format an example that I can test my side to diagnose the issue?

**Comment by ctepelea** [comment]
I am using a Solis S5-EH1P6K-L-DC inverter with an S2 datalogger.

"Could you provide me in txt format an example that I can test my side to diagnose the issue?" - what exactly should I be providing, sorry I don't understand.

I am on 2.1.2 but whatever values I may set for charge/discharte current, any EPM toggles, they revert to their previous values in about a minute or so.

**Comment by ctepelea** [comment]
Hello, any ideas on how to solve this? I am not getting any values sent to the inverter. Reading works.

**Comment by Pho3niX90** [comment]
> Hello, any ideas on how to solve this? I am not getting any values sent to the inverter. Reading works.

Have you tried the latest beta version as yet? There were a lot of changes in regards to the way things are written.

**Comment by ctepelea** [comment]
With version 3.1.1 the issue is closed, writing works timely and flawlessly.
